// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/narrative.proto

package narrative

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NarrativeService_GenerateNarrative_FullMethodName = "/narrative.NarrativeService/GenerateNarrative"
	NarrativeService_GenerateImage_FullMethodName     = "/narrative.NarrativeService/GenerateImage"
)

// NarrativeServiceClient is the client API for NarrativeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NarrativeServiceClient interface {
	GenerateNarrative(ctx context.Context, in *GenerateNarrativeRequest, opts ...grpc.CallOption) (*GenerateNarrativeResponse, error)
	GenerateImage(ctx context.Context, in *GenerateImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
}

type narrativeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNarrativeServiceClient(cc grpc.ClientConnInterface) NarrativeServiceClient {
	return &narrativeServiceClient{cc}
}

func (c *narrativeServiceClient) GenerateNarrative(ctx context.Context, in *GenerateNarrativeRequest, opts ...grpc.CallOption) (*GenerateNarrativeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateNarrativeResponse)
	err := c.cc.Invoke(ctx, NarrativeService_GenerateNarrative_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *narrativeServiceClient) GenerateImage(ctx context.Context, in *GenerateImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, NarrativeService_GenerateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NarrativeServiceServer is the server API for NarrativeService service.
// All implementations must embed UnimplementedNarrativeServiceServer
// for forward compatibility.
type NarrativeServiceServer interface {
	GenerateNarrative(context.Context, *GenerateNarrativeRequest) (*GenerateNarrativeResponse, error)
	GenerateImage(context.Context, *GenerateImageRequest) (*GenerateImageResponse, error)
	mustEmbedUnimplementedNarrativeServiceServer()
}

// UnimplementedNarrativeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNarrativeServiceServer struct{}

func (UnimplementedNarrativeServiceServer) GenerateNarrative(context.Context, *GenerateNarrativeRequest) (*GenerateNarrativeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateNarrative not implemented")
}
func (UnimplementedNarrativeServiceServer) GenerateImage(context.Context, *GenerateImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateImage not implemented")
}
func (UnimplementedNarrativeServiceServer) mustEmbedUnimplementedNarrativeServiceServer() {}
func (UnimplementedNarrativeServiceServer) testEmbeddedByValue()                          {}

// UnsafeNarrativeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NarrativeServiceServer will
// result in compilation errors.
type UnsafeNarrativeServiceServer interface {
	mustEmbedUnimplementedNarrativeServiceServer()
}

func RegisterNarrativeServiceServer(s grpc.ServiceRegistrar, srv NarrativeServiceServer) {
	// If the following call panics, it indicates UnimplementedNarrativeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NarrativeService_ServiceDesc, srv)
}

func _NarrativeService_GenerateNarrative_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateNarrativeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NarrativeServiceServer).GenerateNarrative(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NarrativeService_GenerateNarrative_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NarrativeServiceServer).GenerateNarrative(ctx, req.(*GenerateNarrativeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NarrativeService_GenerateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NarrativeServiceServer).GenerateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NarrativeService_GenerateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NarrativeServiceServer).GenerateImage(ctx, req.(*GenerateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NarrativeService_ServiceDesc is the grpc.ServiceDesc for NarrativeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NarrativeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "narrative.NarrativeService",
	HandlerType: (*NarrativeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateNarrative",
			Handler:    _NarrativeService_GenerateNarrative_Handler,
		},
		{
			MethodName: "GenerateImage",
			Handler:    _NarrativeService_GenerateImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/narrative.proto",
}
