// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/narrative.proto

package narrative

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateNarrativeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Tone          string                 `protobuf:"bytes,2,opt,name=tone,proto3" json:"tone,omitempty"`
	History       []string               `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNarrativeRequest) Reset() {
	*x = GenerateNarrativeRequest{}
	mi := &file_proto_narrative_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNarrativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNarrativeRequest) ProtoMessage() {}

func (x *GenerateNarrativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narrative_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNarrativeRequest.ProtoReflect.Descriptor instead.
func (*GenerateNarrativeRequest) Descriptor() ([]byte, []int) {
	return file_proto_narrative_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateNarrativeRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateNarrativeRequest) GetTone() string {
	if x != nil {
		return x.Tone
	}
	return ""
}

func (x *GenerateNarrativeRequest) GetHistory() []string {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GenerateNarrativeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GenerateNarrativeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNarrativeResponse) Reset() {
	*x = GenerateNarrativeResponse{}
	mi := &file_proto_narrative_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNarrativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNarrativeResponse) ProtoMessage() {}

func (x *GenerateNarrativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narrative_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNarrativeResponse.ProtoReflect.Descriptor instead.
func (*GenerateNarrativeResponse) Descriptor() ([]byte, []int) {
	return file_proto_narrative_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateNarrativeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GenerateAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAudioRequest) Reset() {
	*x = GenerateAudioRequest{}
	mi := &file_proto_narrative_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAudioRequest) ProtoMessage() {}

func (x *GenerateAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narrative_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAudioRequest.ProtoReflect.Descriptor instead.
func (*GenerateAudioRequest) Descriptor() ([]byte, []int) {
	return file_proto_narrative_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateAudioRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateAudioRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GenerateAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAudioResponse) Reset() {
	*x = GenerateAudioResponse{}
	mi := &file_proto_narrative_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAudioResponse) ProtoMessage() {}

func (x *GenerateAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narrative_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAudioResponse.ProtoReflect.Descriptor instead.
func (*GenerateAudioResponse) Descriptor() ([]byte, []int) {
	return file_proto_narrative_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateAudioResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type GenerateImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	PlayerPhoto   *string                `protobuf:"bytes,2,opt,name=player_photo,json=playerPhoto,proto3,oneof" json:"player_photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	mi := &file_proto_narrative_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narrative_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_narrative_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateImageRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateImageRequest) GetPlayerPhoto() string {
	if x != nil && x.PlayerPhoto != nil {
		return *x.PlayerPhoto
	}
	return ""
}

type GenerateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageResponse) Reset() {
	*x = GenerateImageResponse{}
	mi := &file_proto_narrative_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageResponse) ProtoMessage() {}

func (x *GenerateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_narrative_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_narrative_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateImageResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

var File_proto_narrative_proto protoreflect.FileDescriptor

const file_proto_narrative_proto_rawDesc = "" +
	"\n" +
	"\x15proto/narrative.proto\x12\tnarrative\"|\n" +
	"\x18GenerateNarrativeRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04tone\x18\x02 \x01(\tR\x04tone\x12\x18\n" +
	"\ahistory\x18\x03 \x03(\tR\ahistory\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"/\n" +
	"\x19GenerateNarrativeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"F\n" +
	"\x14GenerateAudioRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"6\n" +
	"\x15GenerateAudioResponse\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\"g\n" +
	"\x14GenerateImageRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12&\n" +
	"\fplayer_photo\x18\x02 \x01(\tH\x00R\vplayerPhoto\x88\x01\x01B\x0f\n" +
	"\r_player_photo\"6\n" +
	"\x15GenerateImageResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData2\x9a\x02\n" +
	"\x10NarrativeService\x12^\n" +
	"\x11GenerateNarrative\x12#.narrative.GenerateNarrativeRequest\x1a$.narrative.GenerateNarrativeResponse\x12R\n" +
	"\rGenerateImage\x12\x1f.narrative.GenerateImageRequest\x1a .narrative.GenerateImageResponse\x12R\n" +
	"\rGenerateAudio\x12\x1f.narrative.GenerateAudioRequest\x1a .narrative.GenerateAudioResponseB#Z!random-adventures/proto/narrativeb\x06proto3"

var (
	file_proto_narrative_proto_rawDescOnce sync.Once
	file_proto_narrative_proto_rawDescData []byte
)

func file_proto_narrative_proto_rawDescGZIP() []byte {
	file_proto_narrative_proto_rawDescOnce.Do(func() {
		file_proto_narrative_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_narrative_proto_rawDesc), len(file_proto_narrative_proto_rawDesc)))
	})
	return file_proto_narrative_proto_rawDescData
}

var file_proto_narrative_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_narrative_proto_goTypes = []any{
	(*GenerateNarrativeRequest)(nil),  // 0: narrative.GenerateNarrativeRequest
	(*GenerateNarrativeResponse)(nil), // 1: narrative.GenerateNarrativeResponse
	(*GenerateAudioRequest)(nil),      // 2: narrative.GenerateAudioRequest
	(*GenerateAudioResponse)(nil),     // 3: narrative.GenerateAudioResponse
	(*GenerateImageRequest)(nil),      // 4: narrative.GenerateImageRequest
	(*GenerateImageResponse)(nil),     // 5: narrative.GenerateImageResponse
}
var file_proto_narrative_proto_depIdxs = []int32{
	0, // 0: narrative.NarrativeService.GenerateNarrative:input_type -> narrative.GenerateNarrativeRequest
	4, // 1: narrative.NarrativeService.GenerateImage:input_type -> narrative.GenerateImageRequest
	2, // 2: narrative.NarrativeService.GenerateAudio:input_type -> narrative.GenerateAudioRequest
	1, // 3: narrative.NarrativeService.GenerateNarrative:output_type -> narrative.GenerateNarrativeResponse
	5, // 4: narrative.NarrativeService.GenerateImage:output_type -> narrative.GenerateImageResponse
	3, // 5: narrative.NarrativeService.GenerateAudio:output_type -> narrative.GenerateAudioResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_narrative_proto_init() }
func file_proto_narrative_proto_init() {
	if File_proto_narrative_proto != nil {
		return
	}
	file_proto_narrative_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_narrative_proto_rawDesc), len(file_proto_narrative_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_narrative_proto_goTypes,
		DependencyIndexes: file_proto_narrative_proto_depIdxs,
		MessageInfos:      file_proto_narrative_proto_msgTypes,
	}.Build()
	File_proto_narrative_proto = out.File
	file_proto_narrative_proto_goTypes = nil
	file_proto_narrative_proto_depIdxs = nil
}
