// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/narrative.proto

package narrativeconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	narrative "random-adventures/proto/narrative"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NarrativeServiceName is the fully-qualified name of the NarrativeService service.
	NarrativeServiceName = "narrative.NarrativeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NarrativeServiceGenerateNarrativeProcedure is the fully-qualified name of the NarrativeService's
	// GenerateNarrative RPC.
	NarrativeServiceGenerateNarrativeProcedure = "/narrative.NarrativeService/GenerateNarrative"
	// NarrativeServiceGenerateImageProcedure is the fully-qualified name of the NarrativeService's
	// GenerateImage RPC.
	NarrativeServiceGenerateImageProcedure = "/narrative.NarrativeService/GenerateImage"
	// NarrativeServiceGenerateAudioProcedure is the fully-qualified name of the NarrativeService's
	// GenerateAudio RPC.
	NarrativeServiceGenerateAudioProcedure = "/narrative.NarrativeService/GenerateAudio"
)

// NarrativeServiceClient is a client for the narrative.NarrativeService service.
type NarrativeServiceClient interface {
	GenerateNarrative(context.Context, *connect.Request[narrative.GenerateNarrativeRequest]) (*connect.Response[narrative.GenerateNarrativeResponse], error)
	GenerateImage(context.Context, *connect.Request[narrative.GenerateImageRequest]) (*connect.Response[narrative.GenerateImageResponse], error)
	GenerateAudio(context.Context, *connect.Request[narrative.GenerateAudioRequest]) (*connect.Response[narrative.GenerateAudioResponse], error)
}

// NewNarrativeServiceClient constructs a client for the narrative.NarrativeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNarrativeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NarrativeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	narrativeServiceMethods := narrative.File_proto_narrative_proto.Services().ByName("NarrativeService").Methods()
	return &narrativeServiceClient{
		generateNarrative: connect.NewClient[narrative.GenerateNarrativeRequest, narrative.GenerateNarrativeResponse](
			httpClient,
			baseURL+NarrativeServiceGenerateNarrativeProcedure,
			connect.WithSchema(narrativeServiceMethods.ByName("GenerateNarrative")),
			connect.WithClientOptions(opts...),
		),
		generateImage: connect.NewClient[narrative.GenerateImageRequest, narrative.GenerateImageResponse](
			httpClient,
			baseURL+NarrativeServiceGenerateImageProcedure,
			connect.WithSchema(narrativeServiceMethods.ByName("GenerateImage")),
			connect.WithClientOptions(opts...),
		),
		generateAudio: connect.NewClient[narrative.GenerateAudioRequest, narrative.GenerateAudioResponse](
			httpClient,
			baseURL+NarrativeServiceGenerateAudioProcedure,
			connect.WithSchema(narrativeServiceMethods.ByName("GenerateAudio")),
			connect.WithClientOptions(opts...),
		),
	}
}

// narrativeServiceClient implements NarrativeServiceClient.
type narrativeServiceClient struct {
	generateNarrative *connect.Client[narrative.GenerateNarrativeRequest, narrative.GenerateNarrativeResponse]
	generateImage     *connect.Client[narrative.GenerateImageRequest, narrative.GenerateImageResponse]
	generateAudio     *connect.Client[narrative.GenerateAudioRequest, narrative.GenerateAudioResponse]
}

// GenerateNarrative calls narrative.NarrativeService.GenerateNarrative.
func (c *narrativeServiceClient) GenerateNarrative(ctx context.Context, req *connect.Request[narrative.GenerateNarrativeRequest]) (*connect.Response[narrative.GenerateNarrativeResponse], error) {
	return c.generateNarrative.CallUnary(ctx, req)
}

// GenerateImage calls narrative.NarrativeService.GenerateImage.
func (c *narrativeServiceClient) GenerateImage(ctx context.Context, req *connect.Request[narrative.GenerateImageRequest]) (*connect.Response[narrative.GenerateImageResponse], error) {
	return c.generateImage.CallUnary(ctx, req)
}

// GenerateAudio calls narrative.NarrativeService.GenerateAudio.
func (c *narrativeServiceClient) GenerateAudio(ctx context.Context, req *connect.Request[narrative.GenerateAudioRequest]) (*connect.Response[narrative.GenerateAudioResponse], error) {
	return c.generateAudio.CallUnary(ctx, req)
}

// NarrativeServiceHandler is an implementation of the narrative.NarrativeService service.
type NarrativeServiceHandler interface {
	GenerateNarrative(context.Context, *connect.Request[narrative.GenerateNarrativeRequest]) (*connect.Response[narrative.GenerateNarrativeResponse], error)
	GenerateImage(context.Context, *connect.Request[narrative.GenerateImageRequest]) (*connect.Response[narrative.GenerateImageResponse], error)
	GenerateAudio(context.Context, *connect.Request[narrative.GenerateAudioRequest]) (*connect.Response[narrative.GenerateAudioResponse], error)
}

// NewNarrativeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNarrativeServiceHandler(svc NarrativeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	narrativeServiceMethods := narrative.File_proto_narrative_proto.Services().ByName("NarrativeService").Methods()
	narrativeServiceGenerateNarrativeHandler := connect.NewUnaryHandler(
		NarrativeServiceGenerateNarrativeProcedure,
		svc.GenerateNarrative,
		connect.WithSchema(narrativeServiceMethods.ByName("GenerateNarrative")),
		connect.WithHandlerOptions(opts...),
	)
	narrativeServiceGenerateImageHandler := connect.NewUnaryHandler(
		NarrativeServiceGenerateImageProcedure,
		svc.GenerateImage,
		connect.WithSchema(narrativeServiceMethods.ByName("GenerateImage")),
		connect.WithHandlerOptions(opts...),
	)
	narrativeServiceGenerateAudioHandler := connect.NewUnaryHandler(
		NarrativeServiceGenerateAudioProcedure,
		svc.GenerateAudio,
		connect.WithSchema(narrativeServiceMethods.ByName("GenerateAudio")),
		connect.WithHandlerOptions(opts...),
	)
	return "/narrative.NarrativeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NarrativeServiceGenerateNarrativeProcedure:
			narrativeServiceGenerateNarrativeHandler.ServeHTTP(w, r)
		case NarrativeServiceGenerateImageProcedure:
			narrativeServiceGenerateImageHandler.ServeHTTP(w, r)
		case NarrativeServiceGenerateAudioProcedure:
			narrativeServiceGenerateAudioHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNarrativeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNarrativeServiceHandler struct{}

func (UnimplementedNarrativeServiceHandler) GenerateNarrative(context.Context, *connect.Request[narrative.GenerateNarrativeRequest]) (*connect.Response[narrative.GenerateNarrativeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("narrative.NarrativeService.GenerateNarrative is not implemented"))
}

func (UnimplementedNarrativeServiceHandler) GenerateImage(context.Context, *connect.Request[narrative.GenerateImageRequest]) (*connect.Response[narrative.GenerateImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("narrative.NarrativeService.GenerateImage is not implemented"))
}

func (UnimplementedNarrativeServiceHandler) GenerateAudio(context.Context, *connect.Request[narrative.GenerateAudioRequest]) (*connect.Response[narrative.GenerateAudioResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("narrative.NarrativeService.GenerateAudio is not implemented"))
}
